Attempt to fix missing pkg-config in secp256k1-haskell
Experimental fix for:

```
error: builder for '/nix/store/z7cxiq6ba4bh024d292k31l0cyaa4nvy-secp256k1-haskell-static-x86_64-unknown-linux-musl-0.6.0.drv' failed with exit code 1;
last 10 log lines:
> Dependency cereal >=0.5.4 && <0.6: using cereal-0.5.8.2
> Dependency deepseq >=1.4.2 && <1.5: using deepseq-1.4.4.0
> Dependency entropy >=0.3.8 && <0.5: using entropy-0.4.1.7
> Dependency hashable >=1.2.6 && <1.4: using hashable-1.3.0.0
> Dependency string-conversions ==0.4.*: using string-conversions-0.4.0.1
> Dependency unliftio-core >=0.1.0 && <0.3: using unliftio-core-0.2.0.1
> Setup: The program 'pkg-config' version >=0.9.0 is required but it could not
> be found.
```